"""Identifier generation.

Identifiers are random UUIDs (version 4): non-sequential, so they cannot be enumerated (§9), and
generated by the application, so object keys and rows never depend on user-controlled values (§11).
"""

import uuid


def new_id() -> uuid.UUID:
    return uuid.uuid4()
