"""Write a .env suitable for the critical Playwright suite (fake AI, filesystem storage)."""

from __future__ import annotations

import sys
from pathlib import Path

ENV_BODY = """\
APP_ENV=local
LOG_LEVEL=INFO
LOG_FORMAT=console
REQUEST_ID_HEADER=X-Request-ID
API_DOCS_ENABLED=true
HEALTH_PROBE_TIMEOUT_SECONDS=2
JWT_SECRET=ci-critical-e2e-jwt-secret-at-least-32-chars
JWT_ISSUER=doculens
JWT_AUDIENCE=doculens-api
ACCESS_TOKEN_TTL_SECONDS=900
REFRESH_TOKEN_TTL_SECONDS=2592000
PASSWORD_MIN_LENGTH=12
AUTH_RATE_LIMIT_ATTEMPTS=100
AUTH_RATE_LIMIT_WINDOW_SECONDS=60
POSTGRES_USER=doculens
POSTGRES_PASSWORD=doculens-local-only
POSTGRES_DB=doculens
POSTGRES_PORT=5432
DATABASE_URL=postgresql+asyncpg://doculens:doculens-local-only@127.0.0.1:5432/doculens
DATABASE_POOL_SIZE=5
DATABASE_MAX_OVERFLOW=5
DATABASE_POOL_TIMEOUT_SECONDS=10
DATABASE_POOL_RECYCLE_SECONDS=1800
DATABASE_ECHO=false
REDIS_PORT=6379
REDIS_URL=redis://127.0.0.1:6379/0
QUEUE_BACKEND=redis
QUEUE_NAME=doculens-documents
QUEUE_VISIBILITY_TIMEOUT_SECONDS=300
QUEUE_MAX_ATTEMPTS=5
QUEUE_BACKOFF_BASE_SECONDS=2
QUEUE_BACKOFF_MAX_SECONDS=300
QUEUE_POLL_INTERVAL_SECONDS=1
MAX_FILE_SIZE_MB=50
MAX_PAGES_PER_DOCUMENT=500
MAX_DOCUMENTS_PER_USER=100
PDF_EXTRACTION_TIMEOUT_SECONDS=120
PDF_EXTRACTION_MEMORY_LIMIT_MB=1024
PDF_MAX_CHARACTERS_PER_PAGE=1000000
PDF_MAX_TOTAL_CHARACTERS=20000000
CHUNK_SIZE=512
CHUNK_OVERLAP=64
MIN_CHUNK_SIZE=64
EMBEDDING_PROVIDER=fake
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_API_BASE_URL=https://api.openai.com/v1
EMBEDDING_TIMEOUT_SECONDS=30
EMBEDDING_MAX_ATTEMPTS=4
EMBEDDING_BACKOFF_BASE_SECONDS=0.5
EMBEDDING_BACKOFF_MAX_SECONDS=8
EMBEDDING_MAX_BATCH_SIZE=64
EMBEDDING_MAX_BATCH_CHARACTERS=200000
EMBEDDING_MAX_INPUT_CHARACTERS=32000
EMBEDDING_MAX_CONCURRENCY=4
LLM_PROVIDER=fake
LLM_MODEL=gpt-4o-mini
LLM_API_BASE_URL=https://api.openai.com/v1
LLM_TIMEOUT_SECONDS=60
LLM_MAX_ATTEMPTS=3
LLM_BACKOFF_BASE_SECONDS=1
LLM_BACKOFF_MAX_SECONDS=10
LLM_MAX_OUTPUT_TOKENS=1024
LLM_TEMPERATURE=0
LLM_MAX_INPUT_CHARACTERS=200000
STORAGE_BACKEND=filesystem
STORAGE_LOCAL_ROOT=.local/storage-e2e
STORAGE_BUCKET=doculens-documents
STORAGE_REGION=us-east-1
STORAGE_ENCRYPTION=none
STORAGE_MAX_OBJECT_BYTES=104857600
VECTOR_STORE=chroma
CHROMA_PORT=8001
CHROMA_URL=http://127.0.0.1:8001
CHROMA_COLLECTION_PREFIX=doculens
CHROMA_TIMEOUT_SECONDS=10
VECTOR_SEARCH_MAX_RESULTS=100
INDEXING_BATCH_CHUNKS=128
RETRIEVAL_STRATEGY=hybrid
RETRIEVAL_MAX_QUERY_CHARACTERS=2000
RETRIEVAL_CANDIDATES=20
RETRIEVAL_MIN_SCORE=0
RETRIEVAL_MAX_SCOPE_DOCUMENTS=100
RETRIEVAL_TIMEOUT_SECONDS=15
RERANKER_PROVIDER=none
RERANK_TOP_K=5
RERANK_TIMEOUT_SECONDS=5
CONTEXT_MAX_CHUNKS=5
CONTEXT_MAX_CHARACTERS=12000
CONTEXT_MAX_CHUNKS_PER_DOCUMENT=3
PROMPT_MAX_HISTORY_MESSAGES=10
PROMPT_MAX_HISTORY_CHARACTERS=8000
QUERY_REWRITING=true
QUERY_REWRITE_TIMEOUT_SECONDS=10
GENERATION_TIMEOUT_SECONDS=90
CITATION_MAX_QUOTE_CHARACTERS=500
"""


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parents[1]
    target = Path(argv[1]) if len(argv) > 1 else root / ".env"
    target.write_text(ENV_BODY, encoding="utf-8")
    sys.stdout.write(f"Wrote {target}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
